// The signature sequence: early milestones spaced wide, modern ones dense —
// the spacing itself is the story of acceleration.
export const TIMELINE = [
  {
    key: 'abacus',
    year: 'c. 3000 BC',
    title: 'ABACUS',
    tag: 'CALCULATION',
    body: 'Counting boards appear in Mesopotamia. Calculation becomes a physical act — beads, grooves, memory.',
    pace: 'wide',
  },
  {
    key: 'pascal',
    year: '1642',
    title: 'PASCAL’S CALCULATOR',
    tag: 'MECHANICS',
    body: 'Blaise Pascal builds one of the first mechanical calculators, to help his father with tax arithmetic.',
    pace: 'wide',
  },
  {
    key: 'babbage',
    year: '1833',
    title: 'ANALYTICAL ENGINE',
    tag: 'DESIGN',
    body: 'Charles Babbage designs a machine with a store, a mill and conditional logic — the conceptual shape of a computer.',
    pace: 'mid',
  },
  {
    key: 'lovelace',
    year: '1843',
    title: 'ADA LOVELACE',
    tag: 'PROGRAM',
    body: 'Lovelace publishes notes on the Engine containing what is widely regarded as the first computer program.',
    pace: 'mid',
  },
  {
    key: 'eniac',
    year: '1946',
    title: 'ENIAC',
    tag: 'ELECTRONICS',
    body: 'Electronic computing begins: 30 tons, 17,468 vacuum tubes, 5,000 additions a second.',
    pace: 'mid',
    img: 'eniac-room',
  },
  {
    key: 'microprocessor',
    year: '1971',
    title: 'MICROPROCESSOR',
    tag: 'SILICON',
    body: 'The Intel 4004 puts a computer’s logic on a single chip. The machine begins to shrink.',
    pace: 'dense',
    img: 'silicon-detail',
  },
  {
    key: 'internet',
    year: '1990s',
    title: 'INTERNET',
    tag: 'NETWORK',
    body: 'Machines that calculated alone begin to calculate together.',
    pace: 'dense',
  },
  {
    key: 'bigdata',
    year: '2000s',
    title: 'BIG DATA',
    tag: 'DATA',
    body: 'The world starts generating more information than anyone can read. Scale becomes the problem.',
    pace: 'dense',
  },
  {
    key: 'ml',
    year: '2010s',
    title: 'MACHINE LEARNING',
    tag: 'LEARNING',
    body: 'Instead of being told rules, computers learn patterns from data.',
    pace: 'dense',
  },
  {
    key: 'genai',
    year: '2022+',
    title: 'GENERATIVE AI',
    tag: 'GENERATION',
    body: 'Systems begin to produce text, images, code and audio. The tool starts to create.',
    pace: 'dense',
    img: 'hero-timeline',
  },
];
