// FEATURE 02 — the visual centrepiece of Issue 001.
export default {
  slug: 'eniac',
  no: '02',
  kind: 'FEATURE',
  section: { label: 'TECHNOLOGY', href: '/topics/technology/' },
  topics: ['technology', 'people'],
  runtime: 'the giant',
  title: ['ENIAC'],
  sub: 'THE GIANT THAT STARTED THE DIGITAL AGE',
  dek: 'Before laptops, phones and language models, there was a thirty-ton machine that filled a hall — and six mathematicians who taught it to compute.',
  meta: { date: '1946', read: '6 MIN', ref: 'P. 08', plate: 'PLATE 05' },
  ident: 'ELECTRONIC NUMERICAL INTEGRATOR AND COMPUTER — MOORE SCHOOL OF ELECTRICAL ENGINEERING, UNIVERSITY OF PENNSYLVANIA. DEDICATED 15 FEBRUARY 1946.',
  hero: {
    img: 'eniac-room',
    layout: 'split-left',
    ratio: '3/4',
    caption: 'FIG. 01 — THE MACHINE ROOM. PANELS WIRED BY HAND, UNDER BARE BULBS. 1946.',
    aside: {
      kind: 'contents',
      title: 'IN THIS FEATURE',
      items: ['THE NUMBERS — SIX SPECIFICATIONS', 'THE ENIAC SIX — THE FIRST PROGRAMMERS', 'PROGRAMMING BY HAND, WITHOUT A SCREEN', 'WHAT THE MACHINE LEFT BEHIND'],
      note: 'READING TIME 6 MIN · SPECIFICATION PER GOLDSTINE & GOLDSTINE, 1946',
    },
  },
  blocks: [
    {
      t: 'lede',
      layout: 'narrow',
      text: 'It had no keyboard, no mouse and no screen. It weighed about thirty tons, drew 150 kilowatts, and its one job was arithmetic that people could not do fast enough.',
    },
    { t: 'keynote', layout: 'full', words: ['NO KEYBOARD.', 'NO MOUSE.', 'NO SCREEN.'], note: 'PROGRAMMING MEANT MOVING CABLES, SWITCHES AND PANELS BY HAND. A SINGLE PROBLEM COULD TAKE DAYS TO SET UP.' },
    {
      t: 'statement',
      layout: 'right',
      size: 'lg',
      lines: [
        { text: 'WAR NEEDED SPEED.', size: 'xl' },
        { text: 'The U.S. Army needed artillery firing tables — thousands of ballistic trajectories, and human calculators could not produce them quickly enough. ENIAC was built to do that arithmetic electronically.', size: 'sm' },
      ],
    },
    { t: 'fig', layout: 'bleed', img: 'vacuum-tube', ratio: '21/9', caption: 'FIG. 02 — THE GLOWING HEART OF THE MACHINE. 17,468 VACUUM TUBES, NO MOVING PARTS.' },
    { t: 'specs', layout: 'full', title: 'THE NUMBERS', note: 'THE MACHINE, MEASURED.', tone: 'ink', items: 'eniac', lead: true },
    {
      t: 'roster',
      layout: 'full',
      title: 'THE ENIAC SIX',
      note: 'THEY WERE HIRED AS “COMPUTERS” — PEOPLE WHO DID MATHEMATICS FOR A LIVING. THEY BECAME THE MACHINE’S FIRST PROGRAMMERS, LEARNING ITS HARDWARE FROM ITS SCHEMATICS BECAUSE NO MANUAL EXISTED FOR WHAT THEY WERE DOING.',
      people: [
        { name: 'KAY McNULTY', note: 'LATER MAUCHLY · BALLISTIC TABLES, THEN ENIAC’S TRAJECTORY PROGRAMS' },
        { name: 'BETTY JENNINGS', note: 'LATER BARTIK · WIRED THE MOST COMPLEX PROBLEM OF THE FIRST RUN' },
        { name: 'BETTY SNYDER', note: 'LATER HOLBERTON · PRODUCED THE PRINTED PROGRAM LISTINGS' },
        { name: 'MARLYN WESCOFF', note: 'LATER MELTZER · MASTER OF THE MASTER PROGRAMMING WIRING' },
        { name: 'FRAN BILAS', note: 'LATER SPENCE · DEBUGGED THE MACHINE AT THE PANEL' },
        { name: 'RUTH LICHTERMAN', note: 'LATER TEITELBAUM · HANDLED THE TABLES AND THE RUNS' },
      ],
      footer: 'THEIR NAMES WERE NOT ON THE 1946 PRESS PHOTOGRAPHS. THEY WERE ADDED BY HISTORIANS DECADES LATER.',
    },
    {
      t: 'fig',
      layout: 'wide',
      img: 'eniac-programmers',
      ratio: '3/2',
      caption: 'FIG. 03 — PROGRAMMING BY HAND. THE CABLE WAS THE STATEMENT; THE PANEL WAS THE SOURCE FILE.',
    },
    {
      t: 'chain',
      layout: 'right',
      title: 'WHAT CAME NEXT',
      note: 'ENIAC DID NOT CONTAIN ITS OWN INDUSTRY. IT PROVED ONE WAS POSSIBLE.',
      nodes: ['STORED-PROGRAM COMPUTING', 'MODERN ARCHITECTURE', 'THE COMPUTER INDUSTRY', 'THE DIGITAL WORLD'],
    },
    {
      t: 'pull',
      layout: 'narrow',
      lines: ['THE ARITHMETIC WAS ELECTRONIC.', 'THE JUDGEMENT WAS HUMAN.'],
      cite: 'ON THE ENIAC SIX',
    },
    {
      t: 'statement',
      layout: 'full',
      size: 'lg',
      lines: [
        { text: '1955 — ENIAC WAS SWITCHED OFF.', size: 'md' },
        { text: 'THE IDEA NEVER WAS.', size: 'xl' },
        { text: 'Every laptop, phone and model in use today is downstream of a machine that could not remember its own program.', size: 'sm' },
      ],
    },
  ],
  closing: ['THIRTY TONS OF HISTORY.', 'ONE LINE OF YOURS.'],
  sources: ['eniac-spec', 'eniac-speed', 'eniac-first', 'eniac-six', 'eniac-off'],
};
